package org.ost.entity.org.department;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OrderBy;

@Entity
public class Departments {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.dept_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer deptId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.name
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	@OrderBy
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.description
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.valid
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Byte valid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.is_leaf
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Byte isLeaf;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.parent_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Integer parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.create_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.update_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.creator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String creator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.updator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String updator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.optional1
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String optional1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.optional2
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String optional2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.optional3
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private String optional3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column departments.domain_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	private Integer domainId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.dept_id
	 *
	 * @return the value of departments.dept_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.dept_id
	 *
	 * @param deptId
	 *            the value for departments.dept_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.name
	 *
	 * @return the value of departments.name
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.name
	 *
	 * @param name
	 *            the value for departments.name
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.description
	 *
	 * @return the value of departments.description
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.description
	 *
	 * @param description
	 *            the value for departments.description
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.valid
	 *
	 * @return the value of departments.valid
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Byte getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.valid
	 *
	 * @param valid
	 *            the value for departments.valid
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setValid(Byte valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.is_leaf
	 *
	 * @return the value of departments.is_leaf
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Byte getIsLeaf() {
		return isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.is_leaf
	 *
	 * @param isLeaf
	 *            the value for departments.is_leaf
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setIsLeaf(Byte isLeaf) {
		this.isLeaf = isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.parent_id
	 *
	 * @return the value of departments.parent_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.parent_id
	 *
	 * @param parentId
	 *            the value for departments.parent_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.create_time
	 *
	 * @return the value of departments.create_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.create_time
	 *
	 * @param createTime
	 *            the value for departments.create_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.update_time
	 *
	 * @return the value of departments.update_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.update_time
	 *
	 * @param updateTime
	 *            the value for departments.update_time
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.creator
	 *
	 * @return the value of departments.creator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.creator
	 *
	 * @param creator
	 *            the value for departments.creator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.updator
	 *
	 * @return the value of departments.updator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getUpdator() {
		return updator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.updator
	 *
	 * @param updator
	 *            the value for departments.updator
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setUpdator(String updator) {
		this.updator = updator == null ? null : updator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.optional1
	 *
	 * @return the value of departments.optional1
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getOptional1() {
		return optional1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.optional1
	 *
	 * @param optional1
	 *            the value for departments.optional1
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setOptional1(String optional1) {
		this.optional1 = optional1 == null ? null : optional1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.optional2
	 *
	 * @return the value of departments.optional2
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getOptional2() {
		return optional2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.optional2
	 *
	 * @param optional2
	 *            the value for departments.optional2
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setOptional2(String optional2) {
		this.optional2 = optional2 == null ? null : optional2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.optional3
	 *
	 * @return the value of departments.optional3
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public String getOptional3() {
		return optional3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.optional3
	 *
	 * @param optional3
	 *            the value for departments.optional3
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setOptional3(String optional3) {
		this.optional3 = optional3 == null ? null : optional3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column departments.domain_id
	 *
	 * @return the value of departments.domain_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public Integer getDomainId() {
		return domainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column departments.domain_id
	 *
	 * @param domainId
	 *            the value for departments.domain_id
	 *
	 * @mbggenerated Mon Jan 12 19:17:19 CST 2015
	 */
	public void setDomainId(Integer domainId) {
		this.domainId = domainId;
	}
}