package com.oz.onestong.dao.domain;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.oz.onestong.model.domain.DomainOrder;

public interface DomainOrderMapper {
	
	
	DomainOrder  selectByDomainId(@Param("domainId") Integer domainId);
	
	
	DomainOrder  selectByDomainId(@Param("domainId") Integer domainId,RowBounds rb);

	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    int deleteByPrimaryKey(Integer doId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    int insert(DomainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    int insertSelective(DomainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    DomainOrder selectByPrimaryKey(Integer doId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    int updateByPrimaryKeySelective(DomainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domain_orders
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    int updateByPrimaryKey(DomainOrder record);
}