package com.oz.onestong.dao.event;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.oz.onestong.model.event.AttenceEvent;
import com.oz.onestong.model.event.AttenceEventExample;

public interface AttenceEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int countByExample(AttenceEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int deleteByExample(AttenceEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int deleteByPrimaryKey(String seId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int insert(AttenceEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int insertSelective(AttenceEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     * @param rb 
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    List<AttenceEvent> selectByExample(AttenceEventExample example, RowBounds rb);
    
    
    List<AttenceEvent> selectByExample(AttenceEventExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    AttenceEvent selectByPrimaryKey(String seId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") AttenceEvent record, @Param("example") AttenceEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int updateByExample(@Param("record") AttenceEvent record, @Param("example") AttenceEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int updateByPrimaryKeySelective(AttenceEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_events
     *
     * @mbggenerated Tue Dec 30 14:30:18 CST 2014
     */
    int updateByPrimaryKey(AttenceEvent record);

	List<Map<String, Object>> selectShortCutReportByDepartmentAndMonth(
			@Param("departmentId")  Integer departemtnId, @Param("start") Date start, @Param("end")Date end);

	List<Map<String, Object>> selectShortCutReportByUserAndMonth(
			@Param("userId") Integer userId, @Param("start") Date start, @Param("end") Date end);
	
	
	AttenceEvent selectAttenceEventAndCommentsByEventId( @Param("eventId") String eventId);

	
}