package com.oz.onestong.dao.event;

import com.oz.onestong.model.event.UserTask;
import com.oz.onestong.model.event.UserTaskExample;
import com.oz.onestong.model.event.UserTaskKey;
import com.oz.onestong.model.user.User;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int countByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int deleteByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int deleteByPrimaryKey(UserTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int insert(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int insertSelective(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    List<UserTask> selectByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    UserTask selectByPrimaryKey(UserTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserTask record, @Param("example") UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int updateByExample(@Param("record") UserTask record, @Param("example") UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int updateByPrimaryKeySelective(UserTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbggenerated Mon Apr 13 10:12:05 CST 2015
     */
    int updateByPrimaryKey(UserTask record);
    
    
    List<User> selectUsersByTaskId(@Param("taskId") String taskId);
}