package com.oz.onestong.dao.event;

import com.oz.onestong.dao.event.base.EventBaseMapper;
import com.oz.onestong.model.event.VisitEvent;
import com.oz.onestong.model.event.VisitEventExample;
import com.oz.onestong.model.user.User;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface VisitEventMapper extends EventBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int countByExample(VisitEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int deleteByExample(VisitEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int deleteByPrimaryKey(String veId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int insert(VisitEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int insertSelective(VisitEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	List<VisitEvent> selectByExample(VisitEventExample example);

	List<VisitEvent> selectByExample(VisitEventExample example, RowBounds rb);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	VisitEvent selectByPrimaryKey(String veId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int updateByExampleSelective(@Param("record") VisitEvent record, @Param("example") VisitEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int updateByExample(@Param("record") VisitEvent record, @Param("example") VisitEventExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int updateByPrimaryKeySelective(VisitEvent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table visit_events
	 * 
	 * @mbggenerated Wed Jan 14 10:38:36 CST 2015
	 */
	int updateByPrimaryKey(VisitEvent record);

	VisitEvent selectVisitEventAndCommentsByEventId(@Param("eventId") String eventId);

	List<Map<String, Object>> selectShortCutReportByDepartmentAndMonth(@Param("departmentId") Integer departemtnId,
			@Param("start") Date start, @Param("end") Date end);

	List<Map<String, Object>> selectShortCutReportByUserAndMonth(@Param("userId") Integer userId,
			@Param("start") Date start, @Param("end") Date end);

	/**
	 * 考虑用时间进行分组
	 * 
	 * @param userId
	 * @param start
	 * @param end
	 * @return
	 */
	List<Map<String, Object>> selectMapTrackingDetailReportByUserAndMonth(@Param("userId") Integer userId,
			@Param("start") Date start, @Param("end") Date end);

	@Update("update tbl_visit_event a,(select tveu.id ,#{realname} createBy from tbl_visit_event_user tveu where tveu.userID = #{userId} and tveu.role = 0 ) b"
			+ " set a.createBy  =  b.createBy  where a.id = b.id")
	void updateCreator(User user);

	@Update("update tbl_visit_event_user  set userName = #{realname} where userID = #{userId}")
	void updateVisitUserCreator(User user);

	@Update("update tbl_visit_event_approval_user set userName = #{realname} where userID = #{userId} ")
	void updateVisitApprovalUserCreator(User user);

}