package org.ost.edge.onestong.model.customer;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customer_id
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.name
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.email
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.phone
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.company
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.pic
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.is_public
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private Byte isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.valid
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.create_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.update_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.creator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.updator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.optional1
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.optional2
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.optional3
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String optional3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.tel
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.qq
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.department
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.position
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customer_id
     *
     * @return the value of customers.customer_id
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customer_id
     *
     * @param customerId the value for customers.customer_id
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.name
     *
     * @return the value of customers.name
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.name
     *
     * @param name the value for customers.name
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.email
     *
     * @return the value of customers.email
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.email
     *
     * @param email the value for customers.email
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.phone
     *
     * @return the value of customers.phone
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.phone
     *
     * @param phone the value for customers.phone
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.company
     *
     * @return the value of customers.company
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.company
     *
     * @param company the value for customers.company
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.pic
     *
     * @return the value of customers.pic
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.pic
     *
     * @param pic the value for customers.pic
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.is_public
     *
     * @return the value of customers.is_public
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public Byte getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.is_public
     *
     * @param isPublic the value for customers.is_public
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setIsPublic(Byte isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.valid
     *
     * @return the value of customers.valid
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.valid
     *
     * @param valid the value for customers.valid
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.create_time
     *
     * @return the value of customers.create_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.create_time
     *
     * @param createTime the value for customers.create_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.update_time
     *
     * @return the value of customers.update_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.update_time
     *
     * @param updateTime the value for customers.update_time
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.creator
     *
     * @return the value of customers.creator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.creator
     *
     * @param creator the value for customers.creator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.updator
     *
     * @return the value of customers.updator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.updator
     *
     * @param updator the value for customers.updator
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.optional1
     *
     * @return the value of customers.optional1
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.optional1
     *
     * @param optional1 the value for customers.optional1
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.optional2
     *
     * @return the value of customers.optional2
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.optional2
     *
     * @param optional2 the value for customers.optional2
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.optional3
     *
     * @return the value of customers.optional3
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.optional3
     *
     * @param optional3 the value for customers.optional3
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.tel
     *
     * @return the value of customers.tel
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.tel
     *
     * @param tel the value for customers.tel
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.qq
     *
     * @return the value of customers.qq
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.qq
     *
     * @param qq the value for customers.qq
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.department
     *
     * @return the value of customers.department
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.department
     *
     * @param department the value for customers.department
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.position
     *
     * @return the value of customers.position
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.position
     *
     * @param position the value for customers.position
     *
     * @mbggenerated Tue Jan 20 16:52:15 CST 2015
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}