package org.ost.edge.onestong.model.domain;

import java.util.Date;
import java.util.List;

import org.ost.edge.onestong.tools.Constants;

public class DomainOrder {
	/**
	 * 订单详情
	 */
	private List<DomainOrderDetail> details;
	
	
    public List<DomainOrderDetail> getDetails() {
		return details;
	}

	public void setDetails(List<DomainOrderDetail> details) {
		this.details = details;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.do_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Integer doId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.do_sum
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Integer doSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.domain_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Integer domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.valid
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.optional1
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.optional2
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.optional3
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private String optional3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.creator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.updator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.create_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.update_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.start_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domain_orders.end_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.do_id
     *
     * @return the value of domain_orders.do_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Integer getDoId() {
        return doId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.do_id
     *
     * @param doId the value for domain_orders.do_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setDoId(Integer doId) {
        this.doId = doId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.do_sum
     *
     * @return the value of domain_orders.do_sum
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Integer getDoSum() {
        return doSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.do_sum
     *
     * @param doSum the value for domain_orders.do_sum
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setDoSum(Integer doSum) {
        this.doSum = doSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.domain_id
     *
     * @return the value of domain_orders.domain_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.domain_id
     *
     * @param domainId the value for domain_orders.domain_id
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.valid
     *
     * @return the value of domain_orders.valid
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.valid
     *
     * @param valid the value for domain_orders.valid
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.optional1
     *
     * @return the value of domain_orders.optional1
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.optional1
     *
     * @param optional1 the value for domain_orders.optional1
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.optional2
     *
     * @return the value of domain_orders.optional2
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.optional2
     *
     * @param optional2 the value for domain_orders.optional2
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.optional3
     *
     * @return the value of domain_orders.optional3
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.optional3
     *
     * @param optional3 the value for domain_orders.optional3
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.creator
     *
     * @return the value of domain_orders.creator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.creator
     *
     * @param creator the value for domain_orders.creator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.updator
     *
     * @return the value of domain_orders.updator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.updator
     *
     * @param updator the value for domain_orders.updator
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.create_time
     *
     * @return the value of domain_orders.create_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.create_time
     *
     * @param createTime the value for domain_orders.create_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.update_time
     *
     * @return the value of domain_orders.update_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.update_time
     *
     * @param updateTime the value for domain_orders.update_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.start_time
     *
     * @return the value of domain_orders.start_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.start_time
     *
     * @param startTime the value for domain_orders.start_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domain_orders.end_time
     *
     * @return the value of domain_orders.end_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domain_orders.end_time
     *
     * @param endTime the value for domain_orders.end_time
     *
     * @mbggenerated Sun Jan 11 12:29:44 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}