package org.ost.edge.onestong.model.domain;

import java.io.Serializable;
import java.util.Date;

import org.ost.edge.onestong.tools.Constants;

public class Domain  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3255065227557992688L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.domain_id
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private Integer domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.domain_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.creator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.updator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.create_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.update_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.optional1
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.optional2
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.optional3
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String optional3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.valid
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.company
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.login_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.login_password
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.email
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column domains.state
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.domain_id
     *
     * @return the value of domains.domain_id
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public Integer getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.domain_id
     *
     * @param domainId the value for domains.domain_id
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.domain_name
     *
     * @return the value of domains.domain_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.domain_name
     *
     * @param domainName the value for domains.domain_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.creator
     *
     * @return the value of domains.creator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.creator
     *
     * @param creator the value for domains.creator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.updator
     *
     * @return the value of domains.updator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.updator
     *
     * @param updator the value for domains.updator
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.create_time
     *
     * @return the value of domains.create_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.create_time
     *
     * @param createTime the value for domains.create_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.update_time
     *
     * @return the value of domains.update_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.update_time
     *
     * @param updateTime the value for domains.update_time
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.optional1
     *
     * @return the value of domains.optional1
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.optional1
     *
     * @param optional1 the value for domains.optional1
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.optional2
     *
     * @return the value of domains.optional2
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.optional2
     *
     * @param optional2 the value for domains.optional2
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.optional3
     *
     * @return the value of domains.optional3
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.optional3
     *
     * @param optional3 the value for domains.optional3
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.valid
     *
     * @return the value of domains.valid
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.valid
     *
     * @param valid the value for domains.valid
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.company
     *
     * @return the value of domains.company
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.company
     *
     * @param company the value for domains.company
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.login_name
     *
     * @return the value of domains.login_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.login_name
     *
     * @param loginName the value for domains.login_name
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.login_password
     *
     * @return the value of domains.login_password
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.login_password
     *
     * @param loginPassword the value for domains.login_password
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.email
     *
     * @return the value of domains.email
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.email
     *
     * @param email the value for domains.email
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column domains.state
     *
     * @return the value of domains.state
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column domains.state
     *
     * @param state the value for domains.state
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }
}