package org.ost.edge.onestong.model.user;

import java.io.Serializable;
import java.util.Date;

import org.ost.edge.onestong.model.account.Account;
import org.ost.edge.onestong.tools.Constants;

public class User implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -724411197739453863L;

	/**
	 * 账户
	 */
	private Account account;
	
	
	public User(Integer userId) {
		super();
		this.userId = userId;
	}

	/**
	 * client id 个推 关联用户
	 */
	private String cId;
	
	/**
	 * 个推  别名设置
	 */
	private String  aliasName;
	
	public String getcId() {
		return cId;
	}

	public void setcId(String cId) {
		this.cId = cId;
	}

	public String getAliasName() {
		return aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	/**
	 * 手机号
	 */
	private String phoneNum;
    public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}
	
	/**
	 * 部门名称 新增字段 2015年01月19日10:52:08
	 */
	public String departmentName;
	
	/**
	 * 公司名称
	 */
	public String companyName;
	
	/**
	 * 职位
	 * @return
	 */
	private String position;

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.realname
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.dept_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.state
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Byte state = Constants.USER_NORMAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pic
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_director
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Byte isDirector = Constants.IS_NOT_DEPARTMENT_DIRECTOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Date createTime = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Date updateTime = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional3;

    
    private String deviceId;
    
    public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.realname
     *
     * @return the value of users.realname
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.realname
     *
     * @param realname the value for users.realname
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.dept_id
     *
     * @return the value of users.dept_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.dept_id
     *
     * @param deptId the value for users.dept_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_id
     *
     * @return the value of users.account_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_id
     *
     * @param accountId the value for users.account_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.valid
     *
     * @return the value of users.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.valid
     *
     * @param valid the value for users.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    public User() {
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.state
     *
     * @return the value of users.state
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.state
     *
     * @param state the value for users.state
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pic
     *
     * @return the value of users.pic
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pic
     *
     * @param pic the value for users.pic
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_director
     *
     * @return the value of users.is_director
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Byte getIsDirector() {
        return isDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_director
     *
     * @param isDirector the value for users.is_director
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setIsDirector(Byte isDirector) {
        this.isDirector = isDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.update_time
     *
     * @return the value of users.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.update_time
     *
     * @param updateTime the value for users.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.creator
     *
     * @return the value of users.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.creator
     *
     * @param creator the value for users.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updator
     *
     * @return the value of users.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updator
     *
     * @param updator the value for users.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.optional1
     *
     * @return the value of users.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.optional1
     *
     * @param optional1 the value for users.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.optional2
     *
     * @return the value of users.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.optional2
     *
     * @param optional2 the value for users.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.optional3
     *
     * @return the value of users.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.optional3
     *
     * @param optional3 the value for users.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }
    
    /**
     * 
     */
    private Integer domainId;

	public Integer getDomainId() {
		return domainId;
	}

	public void setDomainId(Integer domainId) {
		this.domainId = domainId;
	}
    
}