package org.ost.edge.onestong.dao.system.location;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ost.edge.onestong.model.system.location.AttenceLocation;
import org.ost.edge.onestong.model.system.location.AttenceLocationExample;

public interface AttenceLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int countByExample(AttenceLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int deleteByExample(AttenceLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int deleteByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int insert(AttenceLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int insertSelective(AttenceLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    List<AttenceLocation> selectByExample(AttenceLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    AttenceLocation selectByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") AttenceLocation record, @Param("example") AttenceLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int updateByExample(@Param("record") AttenceLocation record, @Param("example") AttenceLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int updateByPrimaryKeySelective(AttenceLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attence_location
     *
     * @mbggenerated Wed Jun 17 17:49:56 CST 2015
     */
    int updateByPrimaryKey(AttenceLocation record);
}