package org.ost.edge.onestong.dao.domain;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ost.edge.onestong.model.domain.Domain;
import org.ost.edge.onestong.model.domain.DomainExample;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int countByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int deleteByExample(DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int deleteByPrimaryKey(Integer domainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int insertSelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    List<Domain> selectByExample(DomainExample example);
    List<Domain> selectByExample(DomainExample example,RowBounds rb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    Domain selectByPrimaryKey(Integer domainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int updateByExample(@Param("record") Domain record, @Param("example") DomainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int updateByPrimaryKeySelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table domains
     *
     * @mbggenerated Sat Jan 10 16:56:35 CST 2015
     */
    int updateByPrimaryKey(Domain record);
}