package org.ost.edge.onestong.dao.domain;

import org.apache.ibatis.annotations.Param;
import org.ost.edge.onestong.model.domain.DomainOrderDetail;

public interface DomainOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    int deleteByPrimaryKey(Integer odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    int insert(DomainOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    int insertSelective(DomainOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    DomainOrderDetail selectByPrimaryKey(Integer odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    int updateByPrimaryKeySelective(DomainOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_detail
     *
     * @mbggenerated Sun Jan 11 13:14:45 CST 2015
     */
    int updateByPrimaryKey(DomainOrderDetail record);
    
    
    int countByDomainOrderId(@Param("domainOrderId") Integer orderId);
}