package org.ost.edge.onestong.dao.customer;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ost.edge.onestong.model.customer.CustomerTag;
import org.ost.edge.onestong.model.customer.CustomerTagExample;

public interface CustomerTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int countByExample(CustomerTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int deleteByExample(CustomerTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int deleteByPrimaryKey(Integer ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int insert(CustomerTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int insertSelective(CustomerTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    List<CustomerTag> selectByExample(CustomerTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    CustomerTag selectByPrimaryKey(Integer ctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int updateByExampleSelective(@Param("record") CustomerTag record, @Param("example") CustomerTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int updateByExample(@Param("record") CustomerTag record, @Param("example") CustomerTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int updateByPrimaryKeySelective(CustomerTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_tag
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    int updateByPrimaryKey(CustomerTag record);
}