package org.ost.edge.onestong.model.account;

import java.io.Serializable;
import java.util.Date;

import org.ost.edge.onestong.tools.Constants;

public class Account implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1145285960900779988L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.account_id
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.login_name
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.login_password
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.yixin_account
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String yixinAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.token
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.create_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private Date createTime = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.update_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private Date updateTime = new Date();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.creator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.updator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.valid
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.state
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private Byte state = Constants.USER_NORMAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.optional1
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.optional2
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.optional3
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    private String optional3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.account_id
     *
     * @return the value of accounts.account_id
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.account_id
     *
     * @param accountId the value for accounts.account_id
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.login_name
     *
     * @return the value of accounts.login_name
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.login_name
     *
     * @param loginName the value for accounts.login_name
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.login_password
     *
     * @return the value of accounts.login_password
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.login_password
     *
     * @param loginPassword the value for accounts.login_password
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.yixin_account
     *
     * @return the value of accounts.yixin_account
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getYixinAccount() {
        return yixinAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.yixin_account
     *
     * @param yixinAccount the value for accounts.yixin_account
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setYixinAccount(String yixinAccount) {
        this.yixinAccount = yixinAccount == null ? null : yixinAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.token
     *
     * @return the value of accounts.token
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.token
     *
     * @param token the value for accounts.token
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.create_time
     *
     * @return the value of accounts.create_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.create_time
     *
     * @param createTime the value for accounts.create_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.update_time
     *
     * @return the value of accounts.update_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.update_time
     *
     * @param updateTime the value for accounts.update_time
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.creator
     *
     * @return the value of accounts.creator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.creator
     *
     * @param creator the value for accounts.creator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.updator
     *
     * @return the value of accounts.updator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.updator
     *
     * @param updator the value for accounts.updator
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.valid
     *
     * @return the value of accounts.valid
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.valid
     *
     * @param valid the value for accounts.valid
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.state
     *
     * @return the value of accounts.state
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.state
     *
     * @param state the value for accounts.state
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.optional1
     *
     * @return the value of accounts.optional1
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.optional1
     *
     * @param optional1 the value for accounts.optional1
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.optional2
     *
     * @return the value of accounts.optional2
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.optional2
     *
     * @param optional2 the value for accounts.optional2
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.optional3
     *
     * @return the value of accounts.optional3
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.optional3
     *
     * @param optional3 the value for accounts.optional3
     *
     * @mbggenerated Fri Dec 26 10:05:29 CST 2014
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }
}