package org.ost.edge.onestong.model.scoreSystem;

import java.util.Date;

import org.ost.edge.onestong.tools.Constants;

public class Like {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.like_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.event_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.user_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.create_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.update_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.creator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.updator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.optional2
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.optional3
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String optional3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.optional1
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.valid
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.type
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.like_id
     *
     * @return the value of likes.like_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.like_id
     *
     * @param likeId the value for likes.like_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.event_id
     *
     * @return the value of likes.event_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.event_id
     *
     * @param eventId the value for likes.event_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.user_id
     *
     * @return the value of likes.user_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.user_id
     *
     * @param userId the value for likes.user_id
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.create_time
     *
     * @return the value of likes.create_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.create_time
     *
     * @param createTime the value for likes.create_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.update_time
     *
     * @return the value of likes.update_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.update_time
     *
     * @param updateTime the value for likes.update_time
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.creator
     *
     * @return the value of likes.creator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.creator
     *
     * @param creator the value for likes.creator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.updator
     *
     * @return the value of likes.updator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.updator
     *
     * @param updator the value for likes.updator
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.optional2
     *
     * @return the value of likes.optional2
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.optional2
     *
     * @param optional2 the value for likes.optional2
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.optional3
     *
     * @return the value of likes.optional3
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.optional3
     *
     * @param optional3 the value for likes.optional3
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.optional1
     *
     * @return the value of likes.optional1
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.optional1
     *
     * @param optional1 the value for likes.optional1
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.valid
     *
     * @return the value of likes.valid
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.valid
     *
     * @param valid the value for likes.valid
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.type
     *
     * @return the value of likes.type
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.type
     *
     * @param type the value for likes.type
     *
     * @mbggenerated Wed Jan 14 17:26:02 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }
}