package org.ost.edge.onestong.model.event;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.ost.edge.onestong.model.comment.Comment;
import org.ost.edge.onestong.tools.Constants;

public class AttenceEvent implements Serializable {
	/**
	 * 
	 */
	
	private static final long serialVersionUID = -4648665264902217474L;

	
	private int commentCount;
	private int likeCount;
	
	
	public int getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(int commentCount) {
		this.commentCount = commentCount;
	}

	public int getLikeCount() {
		return likeCount;
	}

	public void setLikeCount(int likeCount) {
		this.likeCount = likeCount;
	}

	/**
	 * 考勤的评论
	 */
	private List<Comment> comments;

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.se_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String seId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.user_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signed_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Date signedTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signed_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signedAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signed_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signedLongitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signed_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signedLatitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signout_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Date signoutTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signout_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signoutAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signout_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signoutLongitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.signout_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String signoutLatitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.state
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.valid
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Byte valid = Constants.DATA_VALID;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.description
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.lated_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Integer latedForTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.le_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Integer leForTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.create_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.update_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.creator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String creator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.updator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String updator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.optional1
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String optional1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.optional2
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String optional2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column attence_events.optional3
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	private String optional3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.se_id
	 * 
	 * @return the value of attence_events.se_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSeId() {
		return seId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.se_id
	 * 
	 * @param seId
	 *            the value for attence_events.se_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSeId(String seId) {
		this.seId = seId == null ? null : seId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.user_id
	 * 
	 * @return the value of attence_events.user_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.user_id
	 * 
	 * @param userId
	 *            the value for attence_events.user_id
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signed_time
	 * 
	 * @return the value of attence_events.signed_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Date getSignedTime() {
		return signedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signed_time
	 * 
	 * @param signedTime
	 *            the value for attence_events.signed_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignedTime(Date signedTime) {
		this.signedTime = signedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signed_address
	 * 
	 * @return the value of attence_events.signed_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignedAddress() {
		return signedAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signed_address
	 * 
	 * @param signedAddress
	 *            the value for attence_events.signed_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignedAddress(String signedAddress) {
		this.signedAddress = signedAddress == null ? null : signedAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signed_longitude
	 * 
	 * @return the value of attence_events.signed_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignedLongitude() {
		return signedLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signed_longitude
	 * 
	 * @param signedLongitude
	 *            the value for attence_events.signed_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignedLongitude(String signedLongitude) {
		this.signedLongitude = signedLongitude == null ? null : signedLongitude
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signed_latitude
	 * 
	 * @return the value of attence_events.signed_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignedLatitude() {
		return signedLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signed_latitude
	 * 
	 * @param signedLatitude
	 *            the value for attence_events.signed_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignedLatitude(String signedLatitude) {
		this.signedLatitude = signedLatitude == null ? null : signedLatitude
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signout_time
	 * 
	 * @return the value of attence_events.signout_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Date getSignoutTime() {
		return signoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signout_time
	 * 
	 * @param signoutTime
	 *            the value for attence_events.signout_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignoutTime(Date signoutTime) {
		this.signoutTime = signoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signout_address
	 * 
	 * @return the value of attence_events.signout_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignoutAddress() {
		return signoutAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signout_address
	 * 
	 * @param signoutAddress
	 *            the value for attence_events.signout_address
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignoutAddress(String signoutAddress) {
		this.signoutAddress = signoutAddress == null ? null : signoutAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signout_longitude
	 * 
	 * @return the value of attence_events.signout_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignoutLongitude() {
		return signoutLongitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signout_longitude
	 * 
	 * @param signoutLongitude
	 *            the value for attence_events.signout_longitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignoutLongitude(String signoutLongitude) {
		this.signoutLongitude = signoutLongitude == null ? null
				: signoutLongitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.signout_latitude
	 * 
	 * @return the value of attence_events.signout_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getSignoutLatitude() {
		return signoutLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.signout_latitude
	 * 
	 * @param signoutLatitude
	 *            the value for attence_events.signout_latitude
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setSignoutLatitude(String signoutLatitude) {
		this.signoutLatitude = signoutLatitude == null ? null : signoutLatitude
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.state
	 * 
	 * @return the value of attence_events.state
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.state
	 * 
	 * @param state
	 *            the value for attence_events.state
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.valid
	 * 
	 * @return the value of attence_events.valid
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Byte getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.valid
	 * 
	 * @param valid
	 *            the value for attence_events.valid
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setValid(Byte valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.description
	 * 
	 * @return the value of attence_events.description
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.description
	 * 
	 * @param description
	 *            the value for attence_events.description
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.lated_for_time
	 * 
	 * @return the value of attence_events.lated_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Integer getLatedForTime() {
		return latedForTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.lated_for_time
	 * 
	 * @param latedForTime
	 *            the value for attence_events.lated_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setLatedForTime(Integer latedForTime) {
		this.latedForTime = latedForTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.le_for_time
	 * 
	 * @return the value of attence_events.le_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Integer getLeForTime() {
		return leForTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.le_for_time
	 * 
	 * @param leForTime
	 *            the value for attence_events.le_for_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setLeForTime(Integer leForTime) {
		this.leForTime = leForTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.create_time
	 * 
	 * @return the value of attence_events.create_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.create_time
	 * 
	 * @param createTime
	 *            the value for attence_events.create_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.update_time
	 * 
	 * @return the value of attence_events.update_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.update_time
	 * 
	 * @param updateTime
	 *            the value for attence_events.update_time
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.creator
	 * 
	 * @return the value of attence_events.creator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.creator
	 * 
	 * @param creator
	 *            the value for attence_events.creator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.updator
	 * 
	 * @return the value of attence_events.updator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getUpdator() {
		return updator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.updator
	 * 
	 * @param updator
	 *            the value for attence_events.updator
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setUpdator(String updator) {
		this.updator = updator == null ? null : updator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.optional1
	 * 
	 * @return the value of attence_events.optional1
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getOptional1() {
		return optional1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.optional1
	 * 
	 * @param optional1
	 *            the value for attence_events.optional1
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setOptional1(String optional1) {
		this.optional1 = optional1 == null ? null : optional1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.optional2
	 * 
	 * @return the value of attence_events.optional2
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getOptional2() {
		return optional2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.optional2
	 * 
	 * @param optional2
	 *            the value for attence_events.optional2
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setOptional2(String optional2) {
		this.optional2 = optional2 == null ? null : optional2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column attence_events.optional3
	 * 
	 * @return the value of attence_events.optional3
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public String getOptional3() {
		return optional3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column attence_events.optional3
	 * 
	 * @param optional3
	 *            the value for attence_events.optional3
	 * 
	 * @mbggenerated Tue Dec 30 14:30:18 CST 2014
	 */
	public void setOptional3(String optional3) {
		this.optional3 = optional3 == null ? null : optional3.trim();
	}
}