package org.ost.edge.onestong.model.event;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DailyEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public DailyEventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeIdIsNull() {
            addCriterion("de_id is null");
            return (Criteria) this;
        }

        public Criteria andDeIdIsNotNull() {
            addCriterion("de_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeIdEqualTo(String value) {
            addCriterion("de_id =", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdNotEqualTo(String value) {
            addCriterion("de_id <>", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdGreaterThan(String value) {
            addCriterion("de_id >", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdGreaterThanOrEqualTo(String value) {
            addCriterion("de_id >=", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdLessThan(String value) {
            addCriterion("de_id <", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdLessThanOrEqualTo(String value) {
            addCriterion("de_id <=", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdLike(String value) {
            addCriterion("de_id like", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdNotLike(String value) {
            addCriterion("de_id not like", value, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdIn(List<String> values) {
            addCriterion("de_id in", values, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdNotIn(List<String> values) {
            addCriterion("de_id not in", values, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdBetween(String value1, String value2) {
            addCriterion("de_id between", value1, value2, "deId");
            return (Criteria) this;
        }

        public Criteria andDeIdNotBetween(String value1, String value2) {
            addCriterion("de_id not between", value1, value2, "deId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("updator is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("updator is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("updator =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("updator <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("updator >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("updator >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("updator <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("updator <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("updator like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("updator not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("updator in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("updator not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("updator between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("updator not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Byte value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }
        
        //state
        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }
        

        public Criteria andValidNotEqualTo(Byte value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Byte value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Byte value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Byte value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Byte> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Byte> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Byte value1, Byte value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Byte value1, Byte value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andOptional1IsNull() {
            addCriterion("optional1 is null");
            return (Criteria) this;
        }

        public Criteria andOptional1IsNotNull() {
            addCriterion("optional1 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional1EqualTo(String value) {
            addCriterion("optional1 =", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotEqualTo(String value) {
            addCriterion("optional1 <>", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1GreaterThan(String value) {
            addCriterion("optional1 >", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1GreaterThanOrEqualTo(String value) {
            addCriterion("optional1 >=", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1LessThan(String value) {
            addCriterion("optional1 <", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1LessThanOrEqualTo(String value) {
            addCriterion("optional1 <=", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1Like(String value) {
            addCriterion("optional1 like", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotLike(String value) {
            addCriterion("optional1 not like", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1In(List<String> values) {
            addCriterion("optional1 in", values, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotIn(List<String> values) {
            addCriterion("optional1 not in", values, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1Between(String value1, String value2) {
            addCriterion("optional1 between", value1, value2, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotBetween(String value1, String value2) {
            addCriterion("optional1 not between", value1, value2, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional2IsNull() {
            addCriterion("optional2 is null");
            return (Criteria) this;
        }

        public Criteria andOptional2IsNotNull() {
            addCriterion("optional2 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional2EqualTo(String value) {
            addCriterion("optional2 =", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotEqualTo(String value) {
            addCriterion("optional2 <>", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2GreaterThan(String value) {
            addCriterion("optional2 >", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2GreaterThanOrEqualTo(String value) {
            addCriterion("optional2 >=", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2LessThan(String value) {
            addCriterion("optional2 <", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2LessThanOrEqualTo(String value) {
            addCriterion("optional2 <=", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2Like(String value) {
            addCriterion("optional2 like", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotLike(String value) {
            addCriterion("optional2 not like", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2In(List<String> values) {
            addCriterion("optional2 in", values, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotIn(List<String> values) {
            addCriterion("optional2 not in", values, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2Between(String value1, String value2) {
            addCriterion("optional2 between", value1, value2, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotBetween(String value1, String value2) {
            addCriterion("optional2 not between", value1, value2, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional3IsNull() {
            addCriterion("optional3 is null");
            return (Criteria) this;
        }

        public Criteria andOptional3IsNotNull() {
            addCriterion("optional3 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional3EqualTo(String value) {
            addCriterion("optional3 =", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotEqualTo(String value) {
            addCriterion("optional3 <>", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3GreaterThan(String value) {
            addCriterion("optional3 >", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3GreaterThanOrEqualTo(String value) {
            addCriterion("optional3 >=", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3LessThan(String value) {
            addCriterion("optional3 <", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3LessThanOrEqualTo(String value) {
            addCriterion("optional3 <=", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3Like(String value) {
            addCriterion("optional3 like", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotLike(String value) {
            addCriterion("optional3 not like", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3In(List<String> values) {
            addCriterion("optional3 in", values, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotIn(List<String> values) {
            addCriterion("optional3 not in", values, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3Between(String value1, String value2) {
            addCriterion("optional3 between", value1, value2, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotBetween(String value1, String value2) {
            addCriterion("optional3 not between", value1, value2, "optional3");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIsNull() {
            addCriterion("device_name is null");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIsNotNull() {
            addCriterion("device_name is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceNameEqualTo(String value) {
            addCriterion("device_name =", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotEqualTo(String value) {
            addCriterion("device_name <>", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameGreaterThan(String value) {
            addCriterion("device_name >", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameGreaterThanOrEqualTo(String value) {
            addCriterion("device_name >=", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLessThan(String value) {
            addCriterion("device_name <", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLessThanOrEqualTo(String value) {
            addCriterion("device_name <=", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameLike(String value) {
            addCriterion("device_name like", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotLike(String value) {
            addCriterion("device_name not like", value, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameIn(List<String> values) {
            addCriterion("device_name in", values, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotIn(List<String> values) {
            addCriterion("device_name not in", values, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameBetween(String value1, String value2) {
            addCriterion("device_name between", value1, value2, "deviceName");
            return (Criteria) this;
        }

        public Criteria andDeviceNameNotBetween(String value1, String value2) {
            addCriterion("device_name not between", value1, value2, "deviceName");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeIsNull() {
            addCriterion("create_longitude is null");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeIsNotNull() {
            addCriterion("create_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeEqualTo(String value) {
            addCriterion("create_longitude =", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeNotEqualTo(String value) {
            addCriterion("create_longitude <>", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeGreaterThan(String value) {
            addCriterion("create_longitude >", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("create_longitude >=", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeLessThan(String value) {
            addCriterion("create_longitude <", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeLessThanOrEqualTo(String value) {
            addCriterion("create_longitude <=", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeLike(String value) {
            addCriterion("create_longitude like", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeNotLike(String value) {
            addCriterion("create_longitude not like", value, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeIn(List<String> values) {
            addCriterion("create_longitude in", values, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeNotIn(List<String> values) {
            addCriterion("create_longitude not in", values, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeBetween(String value1, String value2) {
            addCriterion("create_longitude between", value1, value2, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLongitudeNotBetween(String value1, String value2) {
            addCriterion("create_longitude not between", value1, value2, "createLongitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeIsNull() {
            addCriterion("create_latitude is null");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeIsNotNull() {
            addCriterion("create_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeEqualTo(String value) {
            addCriterion("create_latitude =", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeNotEqualTo(String value) {
            addCriterion("create_latitude <>", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeGreaterThan(String value) {
            addCriterion("create_latitude >", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("create_latitude >=", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeLessThan(String value) {
            addCriterion("create_latitude <", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeLessThanOrEqualTo(String value) {
            addCriterion("create_latitude <=", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeLike(String value) {
            addCriterion("create_latitude like", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeNotLike(String value) {
            addCriterion("create_latitude not like", value, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeIn(List<String> values) {
            addCriterion("create_latitude in", values, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeNotIn(List<String> values) {
            addCriterion("create_latitude not in", values, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeBetween(String value1, String value2) {
            addCriterion("create_latitude between", value1, value2, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andCreateLatitudeNotBetween(String value1, String value2) {
            addCriterion("create_latitude not between", value1, value2, "createLatitude");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNull() {
            addCriterion("like_count is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNotNull() {
            addCriterion("like_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountEqualTo(Integer value) {
            addCriterion("like_count =", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotEqualTo(Integer value) {
            addCriterion("like_count <>", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThan(Integer value) {
            addCriterion("like_count >", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_count >=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThan(Integer value) {
            addCriterion("like_count <", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("like_count <=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIn(List<Integer> values) {
            addCriterion("like_count in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotIn(List<Integer> values) {
            addCriterion("like_count not in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("like_count between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_count not between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNull() {
            addCriterion("event_type is null");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNotNull() {
            addCriterion("event_type is not null");
            return (Criteria) this;
        }

        public Criteria andEventTypeEqualTo(Byte value) {
            addCriterion("event_type =", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotEqualTo(Byte value) {
            addCriterion("event_type <>", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThan(Byte value) {
            addCriterion("event_type >", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("event_type >=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThan(Byte value) {
            addCriterion("event_type <", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThanOrEqualTo(Byte value) {
            addCriterion("event_type <=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeIn(List<Byte> values) {
            addCriterion("event_type in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotIn(List<Byte> values) {
            addCriterion("event_type not in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeBetween(Byte value1, Byte value2) {
            addCriterion("event_type between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("event_type not between", value1, value2, "eventType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table daily_events
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 20 15:42:21 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table daily_events
     *
     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}