package org.ost.edge.onestong.model.event;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VisitEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public VisitEventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVeIdIsNull() {
            addCriterion("ve_id is null");
            return (Criteria) this;
        }

        public Criteria andVeIdIsNotNull() {
            addCriterion("ve_id is not null");
            return (Criteria) this;
        }

        public Criteria andVeIdEqualTo(String value) {
            addCriterion("ve_id =", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdNotEqualTo(String value) {
            addCriterion("ve_id <>", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdGreaterThan(String value) {
            addCriterion("ve_id >", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdGreaterThanOrEqualTo(String value) {
            addCriterion("ve_id >=", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdLessThan(String value) {
            addCriterion("ve_id <", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdLessThanOrEqualTo(String value) {
            addCriterion("ve_id <=", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdLike(String value) {
            addCriterion("ve_id like", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdNotLike(String value) {
            addCriterion("ve_id not like", value, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdIn(List<String> values) {
            addCriterion("ve_id in", values, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdNotIn(List<String> values) {
            addCriterion("ve_id not in", values, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdBetween(String value1, String value2) {
            addCriterion("ve_id between", value1, value2, "veId");
            return (Criteria) this;
        }

        public Criteria andVeIdNotBetween(String value1, String value2) {
            addCriterion("ve_id not between", value1, value2, "veId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Integer value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Integer value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Integer value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Integer value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Integer> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Integer> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeIsNull() {
            addCriterion("visited_time is null");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeIsNotNull() {
            addCriterion("visited_time is not null");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeEqualTo(Date value) {
            addCriterion("visited_time =", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeNotEqualTo(Date value) {
            addCriterion("visited_time <>", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeGreaterThan(Date value) {
            addCriterion("visited_time >", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("visited_time >=", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeLessThan(Date value) {
            addCriterion("visited_time <", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeLessThanOrEqualTo(Date value) {
            addCriterion("visited_time <=", value, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeIn(List<Date> values) {
            addCriterion("visited_time in", values, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeNotIn(List<Date> values) {
            addCriterion("visited_time not in", values, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeBetween(Date value1, Date value2) {
            addCriterion("visited_time between", value1, value2, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVisitedTimeNotBetween(Date value1, Date value2) {
            addCriterion("visited_time not between", value1, value2, "visitedTime");
            return (Criteria) this;
        }

        public Criteria andVistedAddressIsNull() {
            addCriterion("visted_address is null");
            return (Criteria) this;
        }

        public Criteria andVistedAddressIsNotNull() {
            addCriterion("visted_address is not null");
            return (Criteria) this;
        }

        public Criteria andVistedAddressEqualTo(String value) {
            addCriterion("visted_address =", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressNotEqualTo(String value) {
            addCriterion("visted_address <>", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressGreaterThan(String value) {
            addCriterion("visted_address >", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressGreaterThanOrEqualTo(String value) {
            addCriterion("visted_address >=", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressLessThan(String value) {
            addCriterion("visted_address <", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressLessThanOrEqualTo(String value) {
            addCriterion("visted_address <=", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressLike(String value) {
            addCriterion("visted_address like", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressNotLike(String value) {
            addCriterion("visted_address not like", value, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressIn(List<String> values) {
            addCriterion("visted_address in", values, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressNotIn(List<String> values) {
            addCriterion("visted_address not in", values, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressBetween(String value1, String value2) {
            addCriterion("visted_address between", value1, value2, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedAddressNotBetween(String value1, String value2) {
            addCriterion("visted_address not between", value1, value2, "vistedAddress");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeIsNull() {
            addCriterion("visted_longitude is null");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeIsNotNull() {
            addCriterion("visted_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeEqualTo(String value) {
            addCriterion("visted_longitude =", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeNotEqualTo(String value) {
            addCriterion("visted_longitude <>", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeGreaterThan(String value) {
            addCriterion("visted_longitude >", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("visted_longitude >=", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeLessThan(String value) {
            addCriterion("visted_longitude <", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeLessThanOrEqualTo(String value) {
            addCriterion("visted_longitude <=", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeLike(String value) {
            addCriterion("visted_longitude like", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeNotLike(String value) {
            addCriterion("visted_longitude not like", value, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeIn(List<String> values) {
            addCriterion("visted_longitude in", values, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeNotIn(List<String> values) {
            addCriterion("visted_longitude not in", values, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeBetween(String value1, String value2) {
            addCriterion("visted_longitude between", value1, value2, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVistedLongitudeNotBetween(String value1, String value2) {
            addCriterion("visted_longitude not between", value1, value2, "vistedLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeIsNull() {
            addCriterion("visited_latitude is null");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeIsNotNull() {
            addCriterion("visited_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeEqualTo(String value) {
            addCriterion("visited_latitude =", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeNotEqualTo(String value) {
            addCriterion("visited_latitude <>", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeGreaterThan(String value) {
            addCriterion("visited_latitude >", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("visited_latitude >=", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeLessThan(String value) {
            addCriterion("visited_latitude <", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeLessThanOrEqualTo(String value) {
            addCriterion("visited_latitude <=", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeLike(String value) {
            addCriterion("visited_latitude like", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeNotLike(String value) {
            addCriterion("visited_latitude not like", value, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeIn(List<String> values) {
            addCriterion("visited_latitude in", values, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeNotIn(List<String> values) {
            addCriterion("visited_latitude not in", values, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeBetween(String value1, String value2) {
            addCriterion("visited_latitude between", value1, value2, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitedLatitudeNotBetween(String value1, String value2) {
            addCriterion("visited_latitude not between", value1, value2, "visitedLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeIsNull() {
            addCriterion("visitout_time is null");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeIsNotNull() {
            addCriterion("visitout_time is not null");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeEqualTo(Date value) {
            addCriterion("visitout_time =", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeNotEqualTo(Date value) {
            addCriterion("visitout_time <>", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeGreaterThan(Date value) {
            addCriterion("visitout_time >", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("visitout_time >=", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeLessThan(Date value) {
            addCriterion("visitout_time <", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeLessThanOrEqualTo(Date value) {
            addCriterion("visitout_time <=", value, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeIn(List<Date> values) {
            addCriterion("visitout_time in", values, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeNotIn(List<Date> values) {
            addCriterion("visitout_time not in", values, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeBetween(Date value1, Date value2) {
            addCriterion("visitout_time between", value1, value2, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutTimeNotBetween(Date value1, Date value2) {
            addCriterion("visitout_time not between", value1, value2, "visitoutTime");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressIsNull() {
            addCriterion("visitout_address is null");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressIsNotNull() {
            addCriterion("visitout_address is not null");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressEqualTo(String value) {
            addCriterion("visitout_address =", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressNotEqualTo(String value) {
            addCriterion("visitout_address <>", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressGreaterThan(String value) {
            addCriterion("visitout_address >", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressGreaterThanOrEqualTo(String value) {
            addCriterion("visitout_address >=", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressLessThan(String value) {
            addCriterion("visitout_address <", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressLessThanOrEqualTo(String value) {
            addCriterion("visitout_address <=", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressLike(String value) {
            addCriterion("visitout_address like", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressNotLike(String value) {
            addCriterion("visitout_address not like", value, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressIn(List<String> values) {
            addCriterion("visitout_address in", values, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressNotIn(List<String> values) {
            addCriterion("visitout_address not in", values, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressBetween(String value1, String value2) {
            addCriterion("visitout_address between", value1, value2, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutAddressNotBetween(String value1, String value2) {
            addCriterion("visitout_address not between", value1, value2, "visitoutAddress");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeIsNull() {
            addCriterion("visitout_longitude is null");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeIsNotNull() {
            addCriterion("visitout_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeEqualTo(String value) {
            addCriterion("visitout_longitude =", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeNotEqualTo(String value) {
            addCriterion("visitout_longitude <>", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeGreaterThan(String value) {
            addCriterion("visitout_longitude >", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("visitout_longitude >=", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeLessThan(String value) {
            addCriterion("visitout_longitude <", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeLessThanOrEqualTo(String value) {
            addCriterion("visitout_longitude <=", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeLike(String value) {
            addCriterion("visitout_longitude like", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeNotLike(String value) {
            addCriterion("visitout_longitude not like", value, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeIn(List<String> values) {
            addCriterion("visitout_longitude in", values, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeNotIn(List<String> values) {
            addCriterion("visitout_longitude not in", values, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeBetween(String value1, String value2) {
            addCriterion("visitout_longitude between", value1, value2, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLongitudeNotBetween(String value1, String value2) {
            addCriterion("visitout_longitude not between", value1, value2, "visitoutLongitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeIsNull() {
            addCriterion("visitout_latitude is null");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeIsNotNull() {
            addCriterion("visitout_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeEqualTo(String value) {
            addCriterion("visitout_latitude =", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeNotEqualTo(String value) {
            addCriterion("visitout_latitude <>", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeGreaterThan(String value) {
            addCriterion("visitout_latitude >", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("visitout_latitude >=", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeLessThan(String value) {
            addCriterion("visitout_latitude <", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeLessThanOrEqualTo(String value) {
            addCriterion("visitout_latitude <=", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeLike(String value) {
            addCriterion("visitout_latitude like", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeNotLike(String value) {
            addCriterion("visitout_latitude not like", value, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeIn(List<String> values) {
            addCriterion("visitout_latitude in", values, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeNotIn(List<String> values) {
            addCriterion("visitout_latitude not in", values, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeBetween(String value1, String value2) {
            addCriterion("visitout_latitude between", value1, value2, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andVisitoutLatitudeNotBetween(String value1, String value2) {
            addCriterion("visitout_latitude not between", value1, value2, "visitoutLatitude");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("updator is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("updator is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("updator =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("updator <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("updator >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("updator >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("updator <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("updator <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("updator like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("updator not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("updator in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("updator not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("updator between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("updator not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Byte value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Byte value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Byte value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Byte value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Byte value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Byte> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Byte> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Byte value1, Byte value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Byte value1, Byte value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andOptional1IsNull() {
            addCriterion("optional1 is null");
            return (Criteria) this;
        }

        public Criteria andOptional1IsNotNull() {
            addCriterion("optional1 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional1EqualTo(String value) {
            addCriterion("optional1 =", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotEqualTo(String value) {
            addCriterion("optional1 <>", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1GreaterThan(String value) {
            addCriterion("optional1 >", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1GreaterThanOrEqualTo(String value) {
            addCriterion("optional1 >=", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1LessThan(String value) {
            addCriterion("optional1 <", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1LessThanOrEqualTo(String value) {
            addCriterion("optional1 <=", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1Like(String value) {
            addCriterion("optional1 like", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotLike(String value) {
            addCriterion("optional1 not like", value, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1In(List<String> values) {
            addCriterion("optional1 in", values, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotIn(List<String> values) {
            addCriterion("optional1 not in", values, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1Between(String value1, String value2) {
            addCriterion("optional1 between", value1, value2, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional1NotBetween(String value1, String value2) {
            addCriterion("optional1 not between", value1, value2, "optional1");
            return (Criteria) this;
        }

        public Criteria andOptional2IsNull() {
            addCriterion("optional2 is null");
            return (Criteria) this;
        }

        public Criteria andOptional2IsNotNull() {
            addCriterion("optional2 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional2EqualTo(String value) {
            addCriterion("optional2 =", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotEqualTo(String value) {
            addCriterion("optional2 <>", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2GreaterThan(String value) {
            addCriterion("optional2 >", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2GreaterThanOrEqualTo(String value) {
            addCriterion("optional2 >=", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2LessThan(String value) {
            addCriterion("optional2 <", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2LessThanOrEqualTo(String value) {
            addCriterion("optional2 <=", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2Like(String value) {
            addCriterion("optional2 like", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotLike(String value) {
            addCriterion("optional2 not like", value, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2In(List<String> values) {
            addCriterion("optional2 in", values, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotIn(List<String> values) {
            addCriterion("optional2 not in", values, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2Between(String value1, String value2) {
            addCriterion("optional2 between", value1, value2, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional2NotBetween(String value1, String value2) {
            addCriterion("optional2 not between", value1, value2, "optional2");
            return (Criteria) this;
        }

        public Criteria andOptional3IsNull() {
            addCriterion("optional3 is null");
            return (Criteria) this;
        }

        public Criteria andOptional3IsNotNull() {
            addCriterion("optional3 is not null");
            return (Criteria) this;
        }

        public Criteria andOptional3EqualTo(String value) {
            addCriterion("optional3 =", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotEqualTo(String value) {
            addCriterion("optional3 <>", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3GreaterThan(String value) {
            addCriterion("optional3 >", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3GreaterThanOrEqualTo(String value) {
            addCriterion("optional3 >=", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3LessThan(String value) {
            addCriterion("optional3 <", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3LessThanOrEqualTo(String value) {
            addCriterion("optional3 <=", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3Like(String value) {
            addCriterion("optional3 like", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotLike(String value) {
            addCriterion("optional3 not like", value, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3In(List<String> values) {
            addCriterion("optional3 in", values, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotIn(List<String> values) {
            addCriterion("optional3 not in", values, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3Between(String value1, String value2) {
            addCriterion("optional3 between", value1, value2, "optional3");
            return (Criteria) this;
        }

        public Criteria andOptional3NotBetween(String value1, String value2) {
            addCriterion("optional3 not between", value1, value2, "optional3");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryIsNull() {
            addCriterion("visit_summary is null");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryIsNotNull() {
            addCriterion("visit_summary is not null");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryEqualTo(String value) {
            addCriterion("visit_summary =", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryNotEqualTo(String value) {
            addCriterion("visit_summary <>", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryGreaterThan(String value) {
            addCriterion("visit_summary >", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("visit_summary >=", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryLessThan(String value) {
            addCriterion("visit_summary <", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryLessThanOrEqualTo(String value) {
            addCriterion("visit_summary <=", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryLike(String value) {
            addCriterion("visit_summary like", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryNotLike(String value) {
            addCriterion("visit_summary not like", value, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryIn(List<String> values) {
            addCriterion("visit_summary in", values, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryNotIn(List<String> values) {
            addCriterion("visit_summary not in", values, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryBetween(String value1, String value2) {
            addCriterion("visit_summary between", value1, value2, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitSummaryNotBetween(String value1, String value2) {
            addCriterion("visit_summary not between", value1, value2, "visitSummary");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleIsNull() {
            addCriterion("visitout_title is null");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleIsNotNull() {
            addCriterion("visitout_title is not null");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleEqualTo(String value) {
            addCriterion("visitout_title =", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleNotEqualTo(String value) {
            addCriterion("visitout_title <>", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleGreaterThan(String value) {
            addCriterion("visitout_title >", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleGreaterThanOrEqualTo(String value) {
            addCriterion("visitout_title >=", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleLessThan(String value) {
            addCriterion("visitout_title <", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleLessThanOrEqualTo(String value) {
            addCriterion("visitout_title <=", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleLike(String value) {
            addCriterion("visitout_title like", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleNotLike(String value) {
            addCriterion("visitout_title not like", value, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleIn(List<String> values) {
            addCriterion("visitout_title in", values, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleNotIn(List<String> values) {
            addCriterion("visitout_title not in", values, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleBetween(String value1, String value2) {
            addCriterion("visitout_title between", value1, value2, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andVisitoutTitleNotBetween(String value1, String value2) {
            addCriterion("visitout_title not between", value1, value2, "visitoutTitle");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNull() {
            addCriterion("like_count is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNotNull() {
            addCriterion("like_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountEqualTo(Integer value) {
            addCriterion("like_count =", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotEqualTo(Integer value) {
            addCriterion("like_count <>", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThan(Integer value) {
            addCriterion("like_count >", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_count >=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThan(Integer value) {
            addCriterion("like_count <", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("like_count <=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIn(List<Integer> values) {
            addCriterion("like_count in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotIn(List<Integer> values) {
            addCriterion("like_count not in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("like_count between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_count not between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visit_events
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 14 10:38:36 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table visit_events
     *
     * @mbggenerated Wed Jan 14 10:38:36 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}