package com.oz.onestong.model.customer;

import java.util.Date;

import com.oz.onestong.tools.Constants;

public class CustomerTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.ct_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Integer ctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.name
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private Byte valid  = Constants.DATA_VALID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_tag.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    private String optional3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.ct_id
     *
     * @return the value of customer_tag.ct_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.ct_id
     *
     * @param ctId the value for customer_tag.ct_id
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.name
     *
     * @return the value of customer_tag.name
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.name
     *
     * @param name the value for customer_tag.name
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.create_time
     *
     * @return the value of customer_tag.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.create_time
     *
     * @param createTime the value for customer_tag.create_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.update_time
     *
     * @return the value of customer_tag.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.update_time
     *
     * @param updateTime the value for customer_tag.update_time
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.creator
     *
     * @return the value of customer_tag.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.creator
     *
     * @param creator the value for customer_tag.creator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.updator
     *
     * @return the value of customer_tag.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.updator
     *
     * @param updator the value for customer_tag.updator
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.valid
     *
     * @return the value of customer_tag.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.valid
     *
     * @param valid the value for customer_tag.valid
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.optional1
     *
     * @return the value of customer_tag.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.optional1
     *
     * @param optional1 the value for customer_tag.optional1
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.optional2
     *
     * @return the value of customer_tag.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.optional2
     *
     * @param optional2 the value for customer_tag.optional2
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_tag.optional3
     *
     * @return the value of customer_tag.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_tag.optional3
     *
     * @param optional3 the value for customer_tag.optional3
     *
     * @mbggenerated Thu Dec 25 11:03:16 CST 2014
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }
}