package com.oz.onestong.model.comment;

import java.util.Date;

import com.oz.onestong.tools.Constants;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.event_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.creator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.updator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.update_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.to_user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Integer toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.optional1
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String optional1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.optional2
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String optional2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.optional3
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private String optional3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.valid
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    private Byte valid = Constants.DATA_VALID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_id
     *
     * @return the value of comments.comment_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_id
     *
     * @param commentId the value for comments.comment_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.event_id
     *
     * @return the value of comments.event_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.event_id
     *
     * @param eventId the value for comments.event_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.creator
     *
     * @return the value of comments.creator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.creator
     *
     * @param creator the value for comments.creator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.updator
     *
     * @return the value of comments.updator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.updator
     *
     * @param updator the value for comments.updator
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.update_time
     *
     * @return the value of comments.update_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.update_time
     *
     * @param updateTime the value for comments.update_time
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.user_id
     *
     * @return the value of comments.user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.user_id
     *
     * @param userId the value for comments.user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.to_user_id
     *
     * @return the value of comments.to_user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.to_user_id
     *
     * @param toUserId the value for comments.to_user_id
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.optional1
     *
     * @return the value of comments.optional1
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getOptional1() {
        return optional1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.optional1
     *
     * @param optional1 the value for comments.optional1
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setOptional1(String optional1) {
        this.optional1 = optional1 == null ? null : optional1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.optional2
     *
     * @return the value of comments.optional2
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getOptional2() {
        return optional2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.optional2
     *
     * @param optional2 the value for comments.optional2
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setOptional2(String optional2) {
        this.optional2 = optional2 == null ? null : optional2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.optional3
     *
     * @return the value of comments.optional3
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public String getOptional3() {
        return optional3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.optional3
     *
     * @param optional3 the value for comments.optional3
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setOptional3(String optional3) {
        this.optional3 = optional3 == null ? null : optional3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.valid
     *
     * @return the value of comments.valid
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.valid
     *
     * @param valid the value for comments.valid
     *
     * @mbggenerated Wed Jan 14 10:58:28 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}