package org.ost.edge.onestong.dao.event;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ost.edge.onestong.model.event.ApproveEvent;
import org.ost.edge.onestong.model.event.ApproveEventExample;

public interface ApproveEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int countByExample(ApproveEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int deleteByExample(ApproveEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int deleteByPrimaryKey(String aeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int insert(ApproveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int insertSelective(ApproveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    List<ApproveEvent> selectByExample(ApproveEventExample example);
    List<ApproveEvent> selectByExample(ApproveEventExample example,RowBounds rb);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    ApproveEvent selectByPrimaryKey(String aeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") ApproveEvent record, @Param("example") ApproveEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int updateByExample(@Param("record") ApproveEvent record, @Param("example") ApproveEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int updateByPrimaryKeySelective(ApproveEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approve_events
     *
     * @mbggenerated Tue Jan 20 13:36:44 CST 2015
     */
    int updateByPrimaryKey(ApproveEvent record);
}