//package com.oz.onestong.model.event;
//
//import java.util.Date;
//import java.util.List;
//
//import com.oz.onestong.model.comment.Comment;
//import com.oz.onestong.model.resources.Resource;
//import com.oz.onestong.services.api.event.DailyEventService;
//
//public class DailyEvent {
//	
//	/**
//	 * 附件及其他资源  
//	 */
//	private List<Resource> files;
//	
//	
//	public List<Resource> getFiles() {
//		return files;
//	}
//
//	public void setFiles(List<Resource> files) {
//		this.files = files;
//	}
//
//
//
//
//	private List<Comment> comments;
//	
//    public List<Comment> getComments() {
//		return comments;
//	}
//
//	public void setComments(List<Comment> comments) {
//		this.comments = comments;
//	}
//
//	
//	
//	
//	/**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.de_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String deId;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.user_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Integer userId;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.creator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String creator;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.updator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String updator;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.create_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Date createTime;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.update_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Date updateTime;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.valid
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Byte valid;
//    
//    private Byte state = DailyEventService.FLOW_DEFAULT;
//
//    public Byte getState() {
//		return state;
//	}
//
//	public void setState(Byte state) {
//		this.state = state;
//	}
//
//
//
//
//	/**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.optional1
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String optional1;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.optional2
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String optional2;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.optional3
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String optional3;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.device_name
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String deviceName;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.create_longitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String createLongitude;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.create_latitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String createLatitude;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.content
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private String content;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.comment_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Integer commentCount;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.like_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Integer likeCount;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column daily_events.event_type
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    private Byte eventType;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.de_id
//     *
//     * @return the value of daily_events.de_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getDeId() {
//        return deId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.de_id
//     *
//     * @param deId the value for daily_events.de_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setDeId(String deId) {
//        this.deId = deId == null ? null : deId.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.user_id
//     *
//     * @return the value of daily_events.user_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Integer getUserId() {
//        return userId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.user_id
//     *
//     * @param userId the value for daily_events.user_id
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setUserId(Integer userId) {
//        this.userId = userId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.creator
//     *
//     * @return the value of daily_events.creator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getCreator() {
//        return creator;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.creator
//     *
//     * @param creator the value for daily_events.creator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setCreator(String creator) {
//        this.creator = creator == null ? null : creator.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.updator
//     *
//     * @return the value of daily_events.updator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getUpdator() {
//        return updator;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.updator
//     *
//     * @param updator the value for daily_events.updator
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setUpdator(String updator) {
//        this.updator = updator == null ? null : updator.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.create_time
//     *
//     * @return the value of daily_events.create_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Date getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.create_time
//     *
//     * @param createTime the value for daily_events.create_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setCreateTime(Date createTime) {
//        this.createTime = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.update_time
//     *
//     * @return the value of daily_events.update_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Date getUpdateTime() {
//        return updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.update_time
//     *
//     * @param updateTime the value for daily_events.update_time
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setUpdateTime(Date updateTime) {
//        this.updateTime = updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.valid
//     *
//     * @return the value of daily_events.valid
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Byte getValid() {
//        return valid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.valid
//     *
//     * @param valid the value for daily_events.valid
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setValid(Byte valid) {
//        this.valid = valid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.optional1
//     *
//     * @return the value of daily_events.optional1
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getOptional1() {
//        return optional1;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.optional1
//     *
//     * @param optional1 the value for daily_events.optional1
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setOptional1(String optional1) {
//        this.optional1 = optional1 == null ? null : optional1.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.optional2
//     *
//     * @return the value of daily_events.optional2
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getOptional2() {
//        return optional2;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.optional2
//     *
//     * @param optional2 the value for daily_events.optional2
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setOptional2(String optional2) {
//        this.optional2 = optional2 == null ? null : optional2.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.optional3
//     *
//     * @return the value of daily_events.optional3
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getOptional3() {
//        return optional3;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.optional3
//     *
//     * @param optional3 the value for daily_events.optional3
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setOptional3(String optional3) {
//        this.optional3 = optional3 == null ? null : optional3.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.device_name
//     *
//     * @return the value of daily_events.device_name
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getDeviceName() {
//        return deviceName;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.device_name
//     *
//     * @param deviceName the value for daily_events.device_name
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setDeviceName(String deviceName) {
//        this.deviceName = deviceName == null ? null : deviceName.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.create_longitude
//     *
//     * @return the value of daily_events.create_longitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getCreateLongitude() {
//        return createLongitude;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.create_longitude
//     *
//     * @param createLongitude the value for daily_events.create_longitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setCreateLongitude(String createLongitude) {
//        this.createLongitude = createLongitude == null ? null : createLongitude.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.create_latitude
//     *
//     * @return the value of daily_events.create_latitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getCreateLatitude() {
//        return createLatitude;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.create_latitude
//     *
//     * @param createLatitude the value for daily_events.create_latitude
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setCreateLatitude(String createLatitude) {
//        this.createLatitude = createLatitude == null ? null : createLatitude.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.content
//     *
//     * @return the value of daily_events.content
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public String getContent() {
//        return content;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.content
//     *
//     * @param content the value for daily_events.content
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setContent(String content) {
//        this.content = content == null ? null : content.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.comment_count
//     *
//     * @return the value of daily_events.comment_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Integer getCommentCount() {
//        return commentCount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.comment_count
//     *
//     * @param commentCount the value for daily_events.comment_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setCommentCount(Integer commentCount) {
//        this.commentCount = commentCount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.like_count
//     *
//     * @return the value of daily_events.like_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Integer getLikeCount() {
//        return likeCount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.like_count
//     *
//     * @param likeCount the value for daily_events.like_count
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setLikeCount(Integer likeCount) {
//        this.likeCount = likeCount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column daily_events.event_type
//     *
//     * @return the value of daily_events.event_type
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public Byte getEventType() {
//        return eventType;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column daily_events.event_type
//     *
//     * @param eventType the value for daily_events.event_type
//     *
//     * @mbggenerated Tue Jan 20 15:42:21 CST 2015
//     */
//    public void setEventType(Byte eventType) {
//        this.eventType = eventType;
//    }
//}