package org.ost.edge.onestong.dao.tag;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.ost.edge.onestong.model.tag.PTag;
import org.ost.edge.onestong.model.tag.PTagExample;

public interface PTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int countByExample(PTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int deleteByExample(PTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int deleteByPrimaryKey(Integer pTId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int insert(PTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int insertSelective(PTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    List<PTag> selectByExample(PTagExample example);
    List<PTag> selectByExample(PTagExample example,RowBounds rb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    PTag selectByPrimaryKey(Integer pTId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int updateByExampleSelective(@Param("record") PTag record, @Param("example") PTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int updateByExample(@Param("record") PTag record, @Param("example") PTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int updateByPrimaryKeySelective(PTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_tags
     *
     * @mbggenerated Mon Jan 12 11:49:25 CST 2015
     */
    int updateByPrimaryKey(PTag record);
}